name: ci

on:
  push:
    branches: [master, development, 'refactor/unit_tests**', 'epic/**']
  pull_request:
    branches: [master, development, 'refactor/unit_tests**', 'epic/**']
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  build_hummingbot:
    name: build + stable tests
    if: github.event.pull_request.draft == false
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
    
      # Use cache's hashFiles function to check for changes in core code
      - name: Check for code changes
        id: program-changes
        uses: actions/cache@v2
        env:
          # Increase this value to manually reset cache if program files have not changed
          CACHE_NUMBER: 0
        with:
          path: README.md # placeholder file
          key: ${{ runner.os }}-build-${{ env.CACHE_NUMBER }}-${{ hashFiles('hummingbot/*', '**/*.py', '**/*.py*', '**/*.pxd', 'test/*') }}
      
      # Remove envs directory if exists to prevent bin/tar restore errors
      - name: Remove envs directory
        run: rm -Rf /usr/share/miniconda/envs

      # Check for setup/environmnet-linux.yml changes
      - name: Cache conda dependencies
        id: conda-dependencies
        uses: actions/cache@v2
        env:
          # Increase this value to manually reset cache if setup/environment-linux.yml has not changed
          CONDA_CACHE_NUMBER: 0
        with:
          path: |
            /home/runner/conda_pkgs_dir/
            /usr/share/miniconda/envs
          key: ${{ runner.os }}-conda-${{ env.CONDA_CACHE_NUMBER }}-${{ hashFiles('setup/environment-linux.yml') }}

      # Install python/conda to check if core code has changed
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Miniconda and nose
        shell: bash
        run: |
          MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
          curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
          bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda install -c anaconda nose

      # Install pre_commit if code has changed
      - name: Install pre_commit
        shell: bash
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda install -c conda-forge pre_commit
        
      # Install hummingbot env if environment-linux.yml has changed
      - name: Install Hummingbot
        shell: bash -l {0}
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          ./install

      - name: Compile Hummingbot
        shell: bash
        env:
          WITHOUT_CYTHON_OPTIMIZATIONS: true
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda info --envs
          conda activate hummingbot
          conda env export
          ./compile
      - name: Add changes
        shell: bash
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate hummingbot
          python3 setup.py bdist_wheel
          mv dist/*.whl test_build/
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add test_build/*
          git commit -m "Build Hummingbot library"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
